name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    environment: Testing

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          TEST_USERS: ${{ secrets.TEST_USERS }}
          TEST_AUTH: ${{ secrets.TEST_AUTH }}
          TEST_PROFILE: ${{ secrets.TEST_PROFILE }}
          TEST_TWEETS: ${{ secrets.TEST_TWEETS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
        run: yarn test --verbose
