name: CI

environment: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      env:
        MONGO_URI: ${{ Testing.MONGO_URI }}
        TEST_USERS: ${{ Testing.TEST_USERS }}
        TEST_AUTH: ${{ Testing.TEST_AUTH }}
        JWT_SECRET: ${{ Testing.JWT_SECRET }}
        JWT_EXPIRATION: ${{ Testing.JWT_EXPIRATION }}
      run: yarn test
